// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/client.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'mumble/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RustMumbleClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustMumbleClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    dynamic raw,
  );

  @protected
  RustMumbleClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    dynamic raw,
  );

  @protected
  RustMumbleClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    dynamic raw,
  );

  @protected
  RustStreamSink<MumbleEvent> dco_decode_StreamSink_mumble_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioBufferSize dco_decode_audio_buffer_size(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MumbleChannel dco_decode_box_autoadd_mumble_channel(dynamic raw);

  @protected
  MumbleConfig dco_decode_box_autoadd_mumble_config(dynamic raw);

  @protected
  MumbleTextMessage dco_decode_box_autoadd_mumble_text_message(dynamic raw);

  @protected
  MumbleUser dco_decode_box_autoadd_mumble_user(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MumbleChannel dco_decode_mumble_channel(dynamic raw);

  @protected
  MumbleConfig dco_decode_mumble_config(dynamic raw);

  @protected
  MumbleEvent dco_decode_mumble_event(dynamic raw);

  @protected
  MumbleTextMessage dco_decode_mumble_text_message(dynamic raw);

  @protected
  MumbleUser dco_decode_mumble_user(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustMumbleClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    SseDeserializer deserializer,
  );

  @protected
  RustMumbleClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    SseDeserializer deserializer,
  );

  @protected
  RustMumbleClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MumbleEvent> sse_decode_StreamSink_mumble_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioBufferSize sse_decode_audio_buffer_size(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MumbleChannel sse_decode_box_autoadd_mumble_channel(
    SseDeserializer deserializer,
  );

  @protected
  MumbleConfig sse_decode_box_autoadd_mumble_config(
    SseDeserializer deserializer,
  );

  @protected
  MumbleTextMessage sse_decode_box_autoadd_mumble_text_message(
    SseDeserializer deserializer,
  );

  @protected
  MumbleUser sse_decode_box_autoadd_mumble_user(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MumbleChannel sse_decode_mumble_channel(SseDeserializer deserializer);

  @protected
  MumbleConfig sse_decode_mumble_config(SseDeserializer deserializer);

  @protected
  MumbleEvent sse_decode_mumble_event(SseDeserializer deserializer);

  @protected
  MumbleTextMessage sse_decode_mumble_text_message(
    SseDeserializer deserializer,
  );

  @protected
  MumbleUser sse_decode_mumble_user(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    RustMumbleClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    RustMumbleClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    RustMumbleClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_mumble_event_Sse(
    RustStreamSink<MumbleEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_buffer_size(
    AudioBufferSize self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mumble_channel(
    MumbleChannel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mumble_config(
    MumbleConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mumble_text_message(
    MumbleTextMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mumble_user(
    MumbleUser self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mumble_channel(MumbleChannel self, SseSerializer serializer);

  @protected
  void sse_encode_mumble_config(MumbleConfig self, SseSerializer serializer);

  @protected
  void sse_encode_mumble_event(MumbleEvent self, SseSerializer serializer);

  @protected
  void sse_encode_mumble_text_message(
    MumbleTextMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mumble_user(MumbleUser self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    int ptr,
  );
}
