// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'mumble/config.dart';
import 'mumble/hardware/audio.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiClientInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -34741574;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_rumble',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiClientRustMumbleClientConnect({
    required RustMumbleClient that,
    required String host,
    required int port,
    required String username,
    String? password,
  });

  void crateApiClientRustMumbleClientDisconnect({
    required RustMumbleClient that,
  });

  Stream<MumbleEvent> crateApiClientRustMumbleClientGetEventStream({
    required RustMumbleClient that,
  });

  Future<void> crateApiClientRustMumbleClientJoinChannel({
    required RustMumbleClient that,
    required int channelId,
  });

  RustMumbleClient crateApiClientRustMumbleClientNew();

  Future<void> crateApiClientRustMumbleClientSendTextMessage({
    required RustMumbleClient that,
    required String message,
  });

  Future<void> crateApiClientRustMumbleClientSetConfig({
    required RustMumbleClient that,
    required MumbleConfig config,
  });

  Future<void> crateApiClientRustMumbleClientSetDeafen({
    required RustMumbleClient that,
    required bool deafen,
  });

  Future<void> crateApiClientRustMumbleClientSetInputGain({
    required RustMumbleClient that,
    required double gain,
  });

  Future<void> crateApiClientRustMumbleClientSetMute({
    required RustMumbleClient that,
    required bool mute,
  });

  Future<void> crateApiClientRustMumbleClientSetOutputVolume({
    required RustMumbleClient that,
    required double volume,
  });

  Future<void> crateApiClientRustMumbleClientSetPtt({
    required RustMumbleClient that,
    required bool active,
  });

  Future<void> crateApiClientRustMumbleClientSetUserVolume({
    required RustMumbleClient that,
    required int sessionId,
    required double volume,
  });

  Future<void> crateApiClientInitApp();

  Future<List<AudioDevice>> crateApiClientListAudioInputDevices();

  Future<List<AudioDevice>> crateApiClientListAudioOutputDevices();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RustMumbleClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RustMumbleClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RustMumbleClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiClientRustMumbleClientConnect({
    required RustMumbleClient that,
    required String host,
    required int port,
    required String username,
    String? password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
            that,
            serializer,
          );
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientRustMumbleClientConnectConstMeta,
        argValues: [that, host, port, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientConnectConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_connect",
        argNames: ["that", "host", "port", "username", "password"],
      );

  @override
  void crateApiClientRustMumbleClientDisconnect({
    required RustMumbleClient that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustMumbleClientDisconnectConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientDisconnectConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_disconnect",
        argNames: ["that"],
      );

  @override
  Stream<MumbleEvent> crateApiClientRustMumbleClientGetEventStream({
    required RustMumbleClient that,
  }) {
    final sink = RustStreamSink<MumbleEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
              that,
              serializer,
            );
            sse_encode_StreamSink_mumble_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiClientRustMumbleClientGetEventStreamConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientGetEventStreamConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_get_event_stream",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiClientRustMumbleClientJoinChannel({
    required RustMumbleClient that,
    required int channelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
            that,
            serializer,
          );
          sse_encode_u_32(channelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustMumbleClientJoinChannelConstMeta,
        argValues: [that, channelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientJoinChannelConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_join_channel",
        argNames: ["that", "channelId"],
      );

  @override
  RustMumbleClient crateApiClientRustMumbleClientNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustMumbleClientNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientNewConstMeta =>
      const TaskConstMeta(debugName: "RustMumbleClient_new", argNames: []);

  @override
  Future<void> crateApiClientRustMumbleClientSendTextMessage({
    required RustMumbleClient that,
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
            that,
            serializer,
          );
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustMumbleClientSendTextMessageConstMeta,
        argValues: [that, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientSendTextMessageConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_send_text_message",
        argNames: ["that", "message"],
      );

  @override
  Future<void> crateApiClientRustMumbleClientSetConfig({
    required RustMumbleClient that,
    required MumbleConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
            that,
            serializer,
          );
          sse_encode_box_autoadd_mumble_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustMumbleClientSetConfigConstMeta,
        argValues: [that, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientSetConfigConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_set_config",
        argNames: ["that", "config"],
      );

  @override
  Future<void> crateApiClientRustMumbleClientSetDeafen({
    required RustMumbleClient that,
    required bool deafen,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
            that,
            serializer,
          );
          sse_encode_bool(deafen, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustMumbleClientSetDeafenConstMeta,
        argValues: [that, deafen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientSetDeafenConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_set_deafen",
        argNames: ["that", "deafen"],
      );

  @override
  Future<void> crateApiClientRustMumbleClientSetInputGain({
    required RustMumbleClient that,
    required double gain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
            that,
            serializer,
          );
          sse_encode_f_32(gain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustMumbleClientSetInputGainConstMeta,
        argValues: [that, gain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientSetInputGainConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_set_input_gain",
        argNames: ["that", "gain"],
      );

  @override
  Future<void> crateApiClientRustMumbleClientSetMute({
    required RustMumbleClient that,
    required bool mute,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
            that,
            serializer,
          );
          sse_encode_bool(mute, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustMumbleClientSetMuteConstMeta,
        argValues: [that, mute],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientSetMuteConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_set_mute",
        argNames: ["that", "mute"],
      );

  @override
  Future<void> crateApiClientRustMumbleClientSetOutputVolume({
    required RustMumbleClient that,
    required double volume,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
            that,
            serializer,
          );
          sse_encode_f_32(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustMumbleClientSetOutputVolumeConstMeta,
        argValues: [that, volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientSetOutputVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_set_output_volume",
        argNames: ["that", "volume"],
      );

  @override
  Future<void> crateApiClientRustMumbleClientSetPtt({
    required RustMumbleClient that,
    required bool active,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
            that,
            serializer,
          );
          sse_encode_bool(active, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustMumbleClientSetPttConstMeta,
        argValues: [that, active],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientSetPttConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_set_ptt",
        argNames: ["that", "active"],
      );

  @override
  Future<void> crateApiClientRustMumbleClientSetUserVolume({
    required RustMumbleClient that,
    required int sessionId,
    required double volume,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
            that,
            serializer,
          );
          sse_encode_u_32(sessionId, serializer);
          sse_encode_f_32(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustMumbleClientSetUserVolumeConstMeta,
        argValues: [that, sessionId, volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustMumbleClientSetUserVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "RustMumbleClient_set_user_volume",
        argNames: ["that", "sessionId", "volume"],
      );

  @override
  Future<void> crateApiClientInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<AudioDevice>> crateApiClientListAudioInputDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audio_device,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientListAudioInputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientListAudioInputDevicesConstMeta =>
      const TaskConstMeta(debugName: "list_audio_input_devices", argNames: []);

  @override
  Future<List<AudioDevice>> crateApiClientListAudioOutputDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audio_device,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientListAudioOutputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientListAudioOutputDevicesConstMeta =>
      const TaskConstMeta(debugName: "list_audio_output_devices", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RustMumbleClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RustMumbleClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustMumbleClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustMumbleClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustMumbleClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustMumbleClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustMumbleClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustMumbleClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<MumbleEvent> dco_decode_StreamSink_mumble_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioBufferSize dco_decode_audio_buffer_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AudioBufferSize_Default();
      case 1:
        return AudioBufferSize_Fixed(dco_decode_u_32(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  AudioDevice dco_decode_audio_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AudioDevice(
      name: dco_decode_String(arr[0]),
      id: dco_decode_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MumbleChannel dco_decode_box_autoadd_mumble_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mumble_channel(raw);
  }

  @protected
  MumbleConfig dco_decode_box_autoadd_mumble_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mumble_config(raw);
  }

  @protected
  MumbleTextMessage dco_decode_box_autoadd_mumble_text_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mumble_text_message(raw);
  }

  @protected
  MumbleUser dco_decode_box_autoadd_mumble_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mumble_user(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<AudioDevice> dco_decode_list_audio_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audio_device).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MumbleChannel dco_decode_mumble_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MumbleChannel(
      id: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      parentId: dco_decode_opt_box_autoadd_u_32(arr[2]),
      position: dco_decode_i_32(arr[3]),
      description: dco_decode_opt_String(arr[4]),
      isEnterRestricted: dco_decode_bool(arr[5]),
    );
  }

  @protected
  MumbleConfig dco_decode_mumble_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MumbleConfig(
      outgoingAudioBitrate: dco_decode_u_32(arr[0]),
      outgoingAudioMsPerPacket: dco_decode_u_32(arr[1]),
      outgoingOpusComplexity: dco_decode_u_32(arr[2]),
      incomingJitterBufferMs: dco_decode_u_32(arr[3]),
      playbackDeviceId: dco_decode_opt_String(arr[4]),
      playbackHwBufferSize: dco_decode_audio_buffer_size(arr[5]),
      captureHwBufferSize: dco_decode_audio_buffer_size(arr[6]),
      captureDeviceId: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  MumbleEvent dco_decode_mumble_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MumbleEvent_Connected(dco_decode_u_32(raw[1]));
      case 1:
        return MumbleEvent_Disconnected(dco_decode_String(raw[1]));
      case 2:
        return MumbleEvent_ChannelUpdate(
          dco_decode_box_autoadd_mumble_channel(raw[1]),
        );
      case 3:
        return MumbleEvent_UserUpdate(
          dco_decode_box_autoadd_mumble_user(raw[1]),
        );
      case 4:
        return MumbleEvent_UserRemoved(dco_decode_u_32(raw[1]));
      case 5:
        return MumbleEvent_UserTalking(
          dco_decode_u_32(raw[1]),
          dco_decode_bool(raw[2]),
        );
      case 6:
        return MumbleEvent_TextMessage(
          dco_decode_box_autoadd_mumble_text_message(raw[1]),
        );
      case 7:
        return MumbleEvent_AudioVolume(dco_decode_f_32(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  MumbleTextMessage dco_decode_mumble_text_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MumbleTextMessage(
      senderName: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  MumbleUser dco_decode_mumble_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MumbleUser(
      session: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      channelId: dco_decode_u_32(arr[2]),
      isTalking: dco_decode_bool(arr[3]),
      isMuted: dco_decode_bool(arr[4]),
      isDeafened: dco_decode_bool(arr[5]),
      isSuppressed: dco_decode_bool(arr[6]),
      comment: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustMumbleClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustMumbleClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustMumbleClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustMumbleClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustMumbleClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustMumbleClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<MumbleEvent> sse_decode_StreamSink_mumble_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioBufferSize sse_decode_audio_buffer_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return AudioBufferSize_Default();
      case 1:
        var var_field0 = sse_decode_u_32(deserializer);
        return AudioBufferSize_Fixed(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  AudioDevice sse_decode_audio_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_id = sse_decode_String(deserializer);
    return AudioDevice(name: var_name, id: var_id);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MumbleChannel sse_decode_box_autoadd_mumble_channel(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mumble_channel(deserializer));
  }

  @protected
  MumbleConfig sse_decode_box_autoadd_mumble_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mumble_config(deserializer));
  }

  @protected
  MumbleTextMessage sse_decode_box_autoadd_mumble_text_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mumble_text_message(deserializer));
  }

  @protected
  MumbleUser sse_decode_box_autoadd_mumble_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mumble_user(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<AudioDevice> sse_decode_list_audio_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AudioDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audio_device(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MumbleChannel sse_decode_mumble_channel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_parentId = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_position = sse_decode_i_32(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_isEnterRestricted = sse_decode_bool(deserializer);
    return MumbleChannel(
      id: var_id,
      name: var_name,
      parentId: var_parentId,
      position: var_position,
      description: var_description,
      isEnterRestricted: var_isEnterRestricted,
    );
  }

  @protected
  MumbleConfig sse_decode_mumble_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outgoingAudioBitrate = sse_decode_u_32(deserializer);
    var var_outgoingAudioMsPerPacket = sse_decode_u_32(deserializer);
    var var_outgoingOpusComplexity = sse_decode_u_32(deserializer);
    var var_incomingJitterBufferMs = sse_decode_u_32(deserializer);
    var var_playbackDeviceId = sse_decode_opt_String(deserializer);
    var var_playbackHwBufferSize = sse_decode_audio_buffer_size(deserializer);
    var var_captureHwBufferSize = sse_decode_audio_buffer_size(deserializer);
    var var_captureDeviceId = sse_decode_opt_String(deserializer);
    return MumbleConfig(
      outgoingAudioBitrate: var_outgoingAudioBitrate,
      outgoingAudioMsPerPacket: var_outgoingAudioMsPerPacket,
      outgoingOpusComplexity: var_outgoingOpusComplexity,
      incomingJitterBufferMs: var_incomingJitterBufferMs,
      playbackDeviceId: var_playbackDeviceId,
      playbackHwBufferSize: var_playbackHwBufferSize,
      captureHwBufferSize: var_captureHwBufferSize,
      captureDeviceId: var_captureDeviceId,
    );
  }

  @protected
  MumbleEvent sse_decode_mumble_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_u_32(deserializer);
        return MumbleEvent_Connected(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return MumbleEvent_Disconnected(var_field0);
      case 2:
        var var_field0 = sse_decode_box_autoadd_mumble_channel(deserializer);
        return MumbleEvent_ChannelUpdate(var_field0);
      case 3:
        var var_field0 = sse_decode_box_autoadd_mumble_user(deserializer);
        return MumbleEvent_UserUpdate(var_field0);
      case 4:
        var var_field0 = sse_decode_u_32(deserializer);
        return MumbleEvent_UserRemoved(var_field0);
      case 5:
        var var_field0 = sse_decode_u_32(deserializer);
        var var_field1 = sse_decode_bool(deserializer);
        return MumbleEvent_UserTalking(var_field0, var_field1);
      case 6:
        var var_field0 = sse_decode_box_autoadd_mumble_text_message(
          deserializer,
        );
        return MumbleEvent_TextMessage(var_field0);
      case 7:
        var var_field0 = sse_decode_f_32(deserializer);
        return MumbleEvent_AudioVolume(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  MumbleTextMessage sse_decode_mumble_text_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_senderName = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return MumbleTextMessage(senderName: var_senderName, message: var_message);
  }

  @protected
  MumbleUser sse_decode_mumble_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_session = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_channelId = sse_decode_u_32(deserializer);
    var var_isTalking = sse_decode_bool(deserializer);
    var var_isMuted = sse_decode_bool(deserializer);
    var var_isDeafened = sse_decode_bool(deserializer);
    var var_isSuppressed = sse_decode_bool(deserializer);
    var var_comment = sse_decode_opt_String(deserializer);
    return MumbleUser(
      session: var_session,
      name: var_name,
      channelId: var_channelId,
      isTalking: var_isTalking,
      isMuted: var_isMuted,
      isDeafened: var_isDeafened,
      isSuppressed: var_isSuppressed,
      comment: var_comment,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    RustMumbleClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RustMumbleClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    RustMumbleClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RustMumbleClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustMumbleClient(
    RustMumbleClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RustMumbleClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_mumble_event_Sse(
    RustStreamSink<MumbleEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_mumble_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_buffer_size(
    AudioBufferSize self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AudioBufferSize_Default():
        sse_encode_i_32(0, serializer);
      case AudioBufferSize_Fixed(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(field0, serializer);
    }
  }

  @protected
  void sse_encode_audio_device(AudioDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.id, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_mumble_channel(
    MumbleChannel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mumble_channel(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mumble_config(
    MumbleConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mumble_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mumble_text_message(
    MumbleTextMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mumble_text_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mumble_user(
    MumbleUser self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mumble_user(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_audio_device(
    List<AudioDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audio_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mumble_channel(MumbleChannel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_box_autoadd_u_32(self.parentId, serializer);
    sse_encode_i_32(self.position, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_bool(self.isEnterRestricted, serializer);
  }

  @protected
  void sse_encode_mumble_config(MumbleConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.outgoingAudioBitrate, serializer);
    sse_encode_u_32(self.outgoingAudioMsPerPacket, serializer);
    sse_encode_u_32(self.outgoingOpusComplexity, serializer);
    sse_encode_u_32(self.incomingJitterBufferMs, serializer);
    sse_encode_opt_String(self.playbackDeviceId, serializer);
    sse_encode_audio_buffer_size(self.playbackHwBufferSize, serializer);
    sse_encode_audio_buffer_size(self.captureHwBufferSize, serializer);
    sse_encode_opt_String(self.captureDeviceId, serializer);
  }

  @protected
  void sse_encode_mumble_event(MumbleEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MumbleEvent_Connected(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_u_32(field0, serializer);
      case MumbleEvent_Disconnected(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case MumbleEvent_ChannelUpdate(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_mumble_channel(field0, serializer);
      case MumbleEvent_UserUpdate(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_mumble_user(field0, serializer);
      case MumbleEvent_UserRemoved(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_u_32(field0, serializer);
      case MumbleEvent_UserTalking(field0: final field0, field1: final field1):
        sse_encode_i_32(5, serializer);
        sse_encode_u_32(field0, serializer);
        sse_encode_bool(field1, serializer);
      case MumbleEvent_TextMessage(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_box_autoadd_mumble_text_message(field0, serializer);
      case MumbleEvent_AudioVolume(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_f_32(field0, serializer);
    }
  }

  @protected
  void sse_encode_mumble_text_message(
    MumbleTextMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.senderName, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_mumble_user(MumbleUser self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.session, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.channelId, serializer);
    sse_encode_bool(self.isTalking, serializer);
    sse_encode_bool(self.isMuted, serializer);
    sse_encode_bool(self.isDeafened, serializer);
    sse_encode_bool(self.isSuppressed, serializer);
    sse_encode_opt_String(self.comment, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class RustMumbleClientImpl extends RustOpaque implements RustMumbleClient {
  // Not to be used by end users
  RustMumbleClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RustMumbleClientImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RustMumbleClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RustMumbleClient,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_RustMumbleClientPtr,
  );

  Future<void> connect({
    required String host,
    required int port,
    required String username,
    String? password,
  }) => RustLib.instance.api.crateApiClientRustMumbleClientConnect(
    that: this,
    host: host,
    port: port,
    username: username,
    password: password,
  );

  void disconnect() =>
      RustLib.instance.api.crateApiClientRustMumbleClientDisconnect(that: this);

  Stream<MumbleEvent> getEventStream() => RustLib.instance.api
      .crateApiClientRustMumbleClientGetEventStream(that: this);

  Future<void> joinChannel({required int channelId}) =>
      RustLib.instance.api.crateApiClientRustMumbleClientJoinChannel(
        that: this,
        channelId: channelId,
      );

  Future<void> sendTextMessage({required String message}) =>
      RustLib.instance.api.crateApiClientRustMumbleClientSendTextMessage(
        that: this,
        message: message,
      );

  Future<void> setConfig({required MumbleConfig config}) => RustLib.instance.api
      .crateApiClientRustMumbleClientSetConfig(that: this, config: config);

  Future<void> setDeafen({required bool deafen}) => RustLib.instance.api
      .crateApiClientRustMumbleClientSetDeafen(that: this, deafen: deafen);

  Future<void> setInputGain({required double gain}) => RustLib.instance.api
      .crateApiClientRustMumbleClientSetInputGain(that: this, gain: gain);

  Future<void> setMute({required bool mute}) => RustLib.instance.api
      .crateApiClientRustMumbleClientSetMute(that: this, mute: mute);

  Future<void> setOutputVolume({required double volume}) =>
      RustLib.instance.api.crateApiClientRustMumbleClientSetOutputVolume(
        that: this,
        volume: volume,
      );

  Future<void> setPtt({required bool active}) => RustLib.instance.api
      .crateApiClientRustMumbleClientSetPtt(that: this, active: active);

  Future<void> setUserVolume({
    required int sessionId,
    required double volume,
  }) => RustLib.instance.api.crateApiClientRustMumbleClientSetUserVolume(
    that: this,
    sessionId: sessionId,
    volume: volume,
  );
}
