// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

@freezed
sealed class AudioBufferSize with _$AudioBufferSize {
  const AudioBufferSize._();

  /// Use the operating system's default hardware buffer size.
  const factory AudioBufferSize.default_() = AudioBufferSize_Default;

  /// Request a specific hardware buffer size (in frames).
  const factory AudioBufferSize.fixed(int field0) = AudioBufferSize_Fixed;
}

class AudioDevice {
  final String name;
  final String id;

  const AudioDevice({required this.name, required this.id});

  @override
  int get hashCode => name.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDevice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          id == other.id;
}

class MumbleConfig {
  /// Target bitrate for the Opus encoder in bits per second (e.g. 72000).
  final int audioBitrate;

  /// The size of audio chunks sent over the network in milliseconds (e.g. 10ms or 20ms).
  final int audioFrameMs;

  /// Algorithm complexity of the Opus encoder (0-10, default 10).
  final int opusComplexity;

  /// The size of the software jitter buffer in milliseconds.
  /// This intentionally delays playback to handle uneven network packet arrival.
  final int jitterBufferMs;

  /// The requested size of the operating system's hardware audio output buffer.
  final AudioBufferSize outputBufferSize;

  /// The requested size of the operating system's hardware audio input buffer.
  final AudioBufferSize inputBufferSize;

  /// The ID of the audio input device to use. If None, the default device is used.
  final String? inputDeviceId;

  /// The ID of the audio output device to use. If None, the default device is used.
  final String? outputDeviceId;

  const MumbleConfig({
    required this.audioBitrate,
    required this.audioFrameMs,
    required this.opusComplexity,
    required this.jitterBufferMs,
    required this.outputBufferSize,
    required this.inputBufferSize,
    this.inputDeviceId,
    this.outputDeviceId,
  });

  @override
  int get hashCode =>
      audioBitrate.hashCode ^
      audioFrameMs.hashCode ^
      opusComplexity.hashCode ^
      jitterBufferMs.hashCode ^
      outputBufferSize.hashCode ^
      inputBufferSize.hashCode ^
      inputDeviceId.hashCode ^
      outputDeviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MumbleConfig &&
          runtimeType == other.runtimeType &&
          audioBitrate == other.audioBitrate &&
          audioFrameMs == other.audioFrameMs &&
          opusComplexity == other.opusComplexity &&
          jitterBufferMs == other.jitterBufferMs &&
          outputBufferSize == other.outputBufferSize &&
          inputBufferSize == other.inputBufferSize &&
          inputDeviceId == other.inputDeviceId &&
          outputDeviceId == other.outputDeviceId;
}
