// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../mumble/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'client.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `send_command`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<List<AudioDevice>> listAudioInputDevices() =>
    RustLib.instance.api.crateApiClientListAudioInputDevices();

Future<List<AudioDevice>> listAudioOutputDevices() =>
    RustLib.instance.api.crateApiClientListAudioOutputDevices();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RustMumbleClient>>
abstract class RustMumbleClient implements RustOpaqueInterface {
  Stream<MumbleEvent> connect({
    required String host,
    required int port,
    required String username,
    String? password,
  });

  void disconnect();

  Future<void> joinChannel({required int channelId});

  factory RustMumbleClient() =>
      RustLib.instance.api.crateApiClientRustMumbleClientNew();

  Future<void> sendTextMessage({required String message});

  Future<void> setConfig({required MumbleConfig config});

  Future<void> setDeafen({required bool deafen});

  Future<void> setInputGain({required double gain});

  Future<void> setMute({required bool mute});

  Future<void> setOutputVolume({required double volume});

  Future<void> setPtt({required bool active});

  Future<void> setUserVolume({required int sessionId, required double volume});
}

class MumbleChannel {
  final int id;
  final String name;
  final int? parentId;
  final int position;
  final String? description;
  final bool isEnterRestricted;

  const MumbleChannel({
    required this.id,
    required this.name,
    this.parentId,
    required this.position,
    this.description,
    required this.isEnterRestricted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      parentId.hashCode ^
      position.hashCode ^
      description.hashCode ^
      isEnterRestricted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MumbleChannel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId &&
          position == other.position &&
          description == other.description &&
          isEnterRestricted == other.isEnterRestricted;
}

@freezed
sealed class MumbleEvent with _$MumbleEvent {
  const MumbleEvent._();

  const factory MumbleEvent.connected(int field0) = MumbleEvent_Connected;
  const factory MumbleEvent.disconnected(String field0) =
      MumbleEvent_Disconnected;
  const factory MumbleEvent.channelUpdate(MumbleChannel field0) =
      MumbleEvent_ChannelUpdate;
  const factory MumbleEvent.userUpdate(MumbleUser field0) =
      MumbleEvent_UserUpdate;
  const factory MumbleEvent.userRemoved(int field0) = MumbleEvent_UserRemoved;
  const factory MumbleEvent.userTalking(int field0, bool field1) =
      MumbleEvent_UserTalking;
  const factory MumbleEvent.textMessage(MumbleTextMessage field0) =
      MumbleEvent_TextMessage;
  const factory MumbleEvent.audioVolume(double field0) =
      MumbleEvent_AudioVolume;
}

class MumbleTextMessage {
  final String senderName;
  final String message;

  const MumbleTextMessage({required this.senderName, required this.message});

  @override
  int get hashCode => senderName.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MumbleTextMessage &&
          runtimeType == other.runtimeType &&
          senderName == other.senderName &&
          message == other.message;
}

class MumbleUser {
  final int session;
  final String name;
  final int channelId;
  final bool isTalking;
  final bool isMuted;
  final bool isDeafened;
  final bool isSuppressed;
  final String? comment;

  const MumbleUser({
    required this.session,
    required this.name,
    required this.channelId,
    required this.isTalking,
    required this.isMuted,
    required this.isDeafened,
    required this.isSuppressed,
    this.comment,
  });

  @override
  int get hashCode =>
      session.hashCode ^
      name.hashCode ^
      channelId.hashCode ^
      isTalking.hashCode ^
      isMuted.hashCode ^
      isDeafened.hashCode ^
      isSuppressed.hashCode ^
      comment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MumbleUser &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          name == other.name &&
          channelId == other.channelId &&
          isTalking == other.isTalking &&
          isMuted == other.isMuted &&
          isDeafened == other.isDeafened &&
          isSuppressed == other.isSuppressed &&
          comment == other.comment;
}
