// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RustOpusDecoder>>
abstract class RustOpusDecoder implements RustOpaqueInterface {
  Int16List decode({required List<int> opusData, required int frameSize});

  factory RustOpusDecoder({required int sampleRate, required int channels}) =>
      RustLib.instance.api.crateApiOpusRustOpusDecoderNew(
        sampleRate: sampleRate,
        channels: channels,
      );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RustOpusEncoder>>
abstract class RustOpusEncoder implements RustOpaqueInterface {
  Uint8List encode({required List<int> pcm, required int frameSize});

  factory RustOpusEncoder({
    required int sampleRate,
    required int channels,
    required int application,
  }) => RustLib.instance.api.crateApiOpusRustOpusEncoderNew(
    sampleRate: sampleRate,
    channels: channels,
    application: application,
  );

  void setBitrate({required int bitrateBps});
}
