// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RustOpusDecoder>>
abstract class RustOpusDecoder implements RustOpaqueInterface {
  /// ZERO-COPY DECODE
  /// Reads from opus_ptr and writes directly to output_ptr.
  /// Both pointers are managed by Dart (FFI malloc).
  int decodeRaw({
    required BigInt opusPtr,
    required int opusLen,
    required BigInt outputPtr,
    required int frameSize,
  });

  factory RustOpusDecoder({required int sampleRate, required int channels}) =>
      RustLib.instance.api.crateApiOpusRustOpusDecoderNew(
        sampleRate: sampleRate,
        channels: channels,
      );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RustOpusEncoder>>
abstract class RustOpusEncoder implements RustOpaqueInterface {
  /// ZERO-COPY ENCODE
  /// Reads from pcm_ptr and writes directly to output_ptr.
  /// Both pointers are managed by Dart (FFI malloc).
  int encodeRaw({
    required BigInt pcmPtr,
    required int pcmLen,
    required BigInt outputPtr,
    required int outputCapacity,
  });

  factory RustOpusEncoder({
    required int sampleRate,
    required int channels,
    required int application,
  }) => RustLib.instance.api.crateApiOpusRustOpusEncoderNew(
    sampleRate: sampleRate,
    channels: channels,
    application: application,
  );

  void setBitrate({required int bitrateBps});

  void setComplexity({required int complexity});

  void setInbandFec({required bool enabled});

  void setPacketLossPerc({required int percentage});

  void setVbr({required bool vbr});
}
