// Mocks generated by Mockito 5.4.6 from annotations
// in rumble/test/unit/mumble_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i15;

import 'package:dumble/dumble.dart' as _i3;
import 'package:dumble/src/audio/audio_client.dart' as _i6;
import 'package:dumble/src/connection_options.dart' as _i2;
import 'package:dumble/src/listeners.dart' as _i9;
import 'package:dumble/src/model/ban.dart' as _i11;
import 'package:dumble/src/model/channel.dart' as _i5;
import 'package:dumble/src/model/crypto.dart' as _i7;
import 'package:dumble/src/model/text_message.dart' as _i12;
import 'package:dumble/src/model/user.dart' as _i4;
import 'package:dumble/src/model/voice_target.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:record/src/record.dart' as _i14;
import 'package:record_platform_interface/record_platform_interface.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConnectionOptions_0 extends _i1.SmartFake
    implements _i2.ConnectionOptions {
  _FakeConnectionOptions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({bool? tabIndent = true}) => super.toString();
}

class _FakeServerInfo_1 extends _i1.SmartFake implements _i3.ServerInfo {
  _FakeServerInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({bool? tabIndent = true}) => super.toString();
}

class _FakeSelf_2 extends _i1.SmartFake implements _i4.Self {
  _FakeSelf_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({bool? tabIndent = true}) => super.toString();
}

class _FakeChannel_3 extends _i1.SmartFake implements _i5.Channel {
  _FakeChannel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({bool? tabIndent = true}) => super.toString();
}

class _FakeAudioClient_4 extends _i1.SmartFake implements _i6.AudioClient {
  _FakeAudioClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCryptState_5 extends _i1.SmartFake implements _i7.CryptState {
  _FakeCryptState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({bool? tabIndent = true}) => super.toString();
}

class _FakeAmplitude_6 extends _i1.SmartFake implements _i8.Amplitude {
  _FakeAmplitude_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudioFrameSink_7 extends _i1.SmartFake
    implements _i6.AudioFrameSink {
  _FakeAudioFrameSink_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MumbleClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMumbleClient extends _i1.Mock implements _i3.MumbleClient {
  @override
  _i2.ConnectionOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeConnectionOptions_0(
              this,
              Invocation.getter(#options),
            ),
            returnValueForMissingStub: _FakeConnectionOptions_0(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.ConnectionOptions);

  @override
  _i3.ServerInfo get serverInfo =>
      (super.noSuchMethod(
            Invocation.getter(#serverInfo),
            returnValue: _FakeServerInfo_1(
              this,
              Invocation.getter(#serverInfo),
            ),
            returnValueForMissingStub: _FakeServerInfo_1(
              this,
              Invocation.getter(#serverInfo),
            ),
          )
          as _i3.ServerInfo);

  @override
  _i4.Self get self =>
      (super.noSuchMethod(
            Invocation.getter(#self),
            returnValue: _FakeSelf_2(this, Invocation.getter(#self)),
            returnValueForMissingStub: _FakeSelf_2(
              this,
              Invocation.getter(#self),
            ),
          )
          as _i4.Self);

  @override
  _i5.Channel get rootChannel =>
      (super.noSuchMethod(
            Invocation.getter(#rootChannel),
            returnValue: _FakeChannel_3(this, Invocation.getter(#rootChannel)),
            returnValueForMissingStub: _FakeChannel_3(
              this,
              Invocation.getter(#rootChannel),
            ),
          )
          as _i5.Channel);

  @override
  _i6.AudioClient get audio =>
      (super.noSuchMethod(
            Invocation.getter(#audio),
            returnValue: _FakeAudioClient_4(this, Invocation.getter(#audio)),
            returnValueForMissingStub: _FakeAudioClient_4(
              this,
              Invocation.getter(#audio),
            ),
          )
          as _i6.AudioClient);

  @override
  bool get closed =>
      (super.noSuchMethod(
            Invocation.getter(#closed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Iterable<_i9.MumbleClientListener> get listeners =>
      (super.noSuchMethod(
            Invocation.getter(#listeners),
            returnValue: <_i9.MumbleClientListener>[],
            returnValueForMissingStub: <_i9.MumbleClientListener>[],
          )
          as Iterable<_i9.MumbleClientListener>);

  @override
  _i7.CryptState get cryptState =>
      (super.noSuchMethod(
            Invocation.getter(#cryptState),
            returnValue: _FakeCryptState_5(
              this,
              Invocation.getter(#cryptState),
            ),
            returnValueForMissingStub: _FakeCryptState_5(
              this,
              Invocation.getter(#cryptState),
            ),
          )
          as _i7.CryptState);

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  Map<int, _i4.User> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: <int, _i4.User>{},
            returnValueForMissingStub: <int, _i4.User>{},
          )
          as Map<int, _i4.User>);

  @override
  Map<int, _i5.Channel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <int, _i5.Channel>{},
            returnValueForMissingStub: <int, _i5.Channel>{},
          )
          as Map<int, _i5.Channel>);

  @override
  void setBanList(List<_i11.BanEntry>? bans) => super.noSuchMethod(
    Invocation.method(#setBanList, [bans]),
    returnValueForMissingStub: null,
  );

  @override
  void queryBans() => super.noSuchMethod(
    Invocation.method(#queryBans, []),
    returnValueForMissingStub: null,
  );

  @override
  void listUsers() => super.noSuchMethod(
    Invocation.method(#listUsers, []),
    returnValueForMissingStub: null,
  );

  @override
  void queryUsersByNames({required List<String>? names}) => super.noSuchMethod(
    Invocation.method(#queryUsersByNames, [], {#names: names}),
    returnValueForMissingStub: null,
  );

  @override
  void queryUsersByIds({required List<int>? ids}) => super.noSuchMethod(
    Invocation.method(#queryUsersByIds, [], {#ids: ids}),
    returnValueForMissingStub: null,
  );

  @override
  void updateTokens({required List<String>? tokens}) => super.noSuchMethod(
    Invocation.method(#updateTokens, [], {#tokens: tokens}),
    returnValueForMissingStub: null,
  );

  @override
  void createChannel({
    required String? name,
    int? position,
    int? maxUsers,
    String? description,
    bool? temporary,
    _i5.Channel? parent,
  }) => super.noSuchMethod(
    Invocation.method(#createChannel, [], {
      #name: name,
      #position: position,
      #maxUsers: maxUsers,
      #description: description,
      #temporary: temporary,
      #parent: parent,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void sendMessage({required _i12.OutgoingTextMessage? message}) =>
      super.noSuchMethod(
        Invocation.method(#sendMessage, [], {#message: message}),
        returnValueForMissingStub: null,
      );

  @override
  void registerVoiceTarget({required _i13.VoiceTarget? target}) =>
      super.noSuchMethod(
        Invocation.method(#registerVoiceTarget, [], {#target: target}),
        returnValueForMissingStub: null,
      );

  @override
  void requestCryptStateResync() => super.noSuchMethod(
    Invocation.method(#requestCryptStateResync, []),
    returnValueForMissingStub: null,
  );

  @override
  void add(_i9.MumbleClientListener? listener) => super.noSuchMethod(
    Invocation.method(#add, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void remove(_i9.MumbleClientListener? listener) => super.noSuchMethod(
    Invocation.method(#remove, [listener]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AudioRecorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRecorder extends _i1.Mock implements _i14.AudioRecorder {
  @override
  _i10.Future<void> start(_i8.RecordConfig? config, {required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#start, [config], {#path: path}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i10.Stream<_i15.Uint8List>> startStream(
    _i8.RecordConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startStream, [config]),
            returnValue: _i10.Future<_i10.Stream<_i15.Uint8List>>.value(
              _i10.Stream<_i15.Uint8List>.empty(),
            ),
            returnValueForMissingStub:
                _i10.Future<_i10.Stream<_i15.Uint8List>>.value(
                  _i10.Stream<_i15.Uint8List>.empty(),
                ),
          )
          as _i10.Future<_i10.Stream<_i15.Uint8List>>);

  @override
  _i10.Future<String?> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i10.Future<String?>.value(),
            returnValueForMissingStub: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<void> cancel() =>
      (super.noSuchMethod(
            Invocation.method(#cancel, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> isRecording() =>
      (super.noSuchMethod(
            Invocation.method(#isRecording, []),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> isPaused() =>
      (super.noSuchMethod(
            Invocation.method(#isPaused, []),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> hasPermission({bool? request = true}) =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, [], {#request: request}),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<_i8.InputDevice>> listInputDevices() =>
      (super.noSuchMethod(
            Invocation.method(#listInputDevices, []),
            returnValue: _i10.Future<List<_i8.InputDevice>>.value(
              <_i8.InputDevice>[],
            ),
            returnValueForMissingStub: _i10.Future<List<_i8.InputDevice>>.value(
              <_i8.InputDevice>[],
            ),
          )
          as _i10.Future<List<_i8.InputDevice>>);

  @override
  _i10.Future<_i8.Amplitude> getAmplitude() =>
      (super.noSuchMethod(
            Invocation.method(#getAmplitude, []),
            returnValue: _i10.Future<_i8.Amplitude>.value(
              _FakeAmplitude_6(this, Invocation.method(#getAmplitude, [])),
            ),
            returnValueForMissingStub: _i10.Future<_i8.Amplitude>.value(
              _FakeAmplitude_6(this, Invocation.method(#getAmplitude, [])),
            ),
          )
          as _i10.Future<_i8.Amplitude>);

  @override
  _i10.Future<bool> isEncoderSupported(_i8.AudioEncoder? encoder) =>
      (super.noSuchMethod(
            Invocation.method(#isEncoderSupported, [encoder]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Stream<_i8.RecordState> onStateChanged() =>
      (super.noSuchMethod(
            Invocation.method(#onStateChanged, []),
            returnValue: _i10.Stream<_i8.RecordState>.empty(),
            returnValueForMissingStub: _i10.Stream<_i8.RecordState>.empty(),
          )
          as _i10.Stream<_i8.RecordState>);

  @override
  _i10.Stream<_i8.Amplitude> onAmplitudeChanged(Duration? interval) =>
      (super.noSuchMethod(
            Invocation.method(#onAmplitudeChanged, [interval]),
            returnValue: _i10.Stream<_i8.Amplitude>.empty(),
            returnValueForMissingStub: _i10.Stream<_i8.Amplitude>.empty(),
          )
          as _i10.Stream<_i8.Amplitude>);

  @override
  List<int> convertBytesToInt16(
    _i15.Uint8List? bytes, [
    _i15.Endian? endian = _i15.Endian.little,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#convertBytesToInt16, [bytes, endian]),
            returnValue: <int>[],
            returnValueForMissingStub: <int>[],
          )
          as List<int>);
}

/// A class which mocks [AudioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioClient extends _i1.Mock implements _i6.AudioClient {
  @override
  bool get shouldUseUdp =>
      (super.noSuchMethod(
            Invocation.getter(#shouldUseUdp),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get udpCurrentlyAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#udpCurrentlyAvailable),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Iterable<_i9.AudioListener> get listeners =>
      (super.noSuchMethod(
            Invocation.getter(#listeners),
            returnValue: <_i9.AudioListener>[],
            returnValueForMissingStub: <_i9.AudioListener>[],
          )
          as Iterable<_i9.AudioListener>);

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i6.AudioFrameSink sendAudio({
    required _i3.AudioCodec? codec,
    int? voiceTarget = 0,
    int? framesPerPacket,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendAudio, [], {
              #codec: codec,
              #voiceTarget: voiceTarget,
              #framesPerPacket: framesPerPacket,
            }),
            returnValue: _FakeAudioFrameSink_7(
              this,
              Invocation.method(#sendAudio, [], {
                #codec: codec,
                #voiceTarget: voiceTarget,
                #framesPerPacket: framesPerPacket,
              }),
            ),
            returnValueForMissingStub: _FakeAudioFrameSink_7(
              this,
              Invocation.method(#sendAudio, [], {
                #codec: codec,
                #voiceTarget: voiceTarget,
                #framesPerPacket: framesPerPacket,
              }),
            ),
          )
          as _i6.AudioFrameSink);

  @override
  void add(_i9.AudioListener? listener) => super.noSuchMethod(
    Invocation.method(#add, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void remove(_i9.AudioListener? listener) => super.noSuchMethod(
    Invocation.method(#remove, [listener]),
    returnValueForMissingStub: null,
  );
}
